### ISSUE TITLE
"charts/semantic-hub" is missing in the released version of semantic-hub-0.4.0

### ISSUE THREAD

**Issue by FaridLU** [eclipse-tractusx/sldt-semantic-hub#301]
### Description
I have tried the latest release of Semantic Hub, [semantic-hub-0.4.0](https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/semantic-hub-0.4.0).  I tried to run the project with the guidelines provided in `readme.md`. It didn't work as expected.

### Current Behavior
After creating the namespace, using kubectl, when I tried to install the `chats/semantics` using helm, it said **Error: INSTALLATION FAILED: repo charts not found**

### Expected Behavior
The `charts/semantic-hub` should be present in the released version.

### Steps To Reproduce
Follow the steps below to reproduce the issue:

1. Download the [released version](https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/semantic-hub-0.4.0)
![image](https://github.com/user-attachments/assets/4ca29463-b9d2-4850-8937-6e0288f2b21a)

2. Unzip and open the terminal in that folder.
3. Try to follow the instructions defined in the README.md
![image](https://github.com/user-attachments/assets/e3010f87-49dc-4418-8a5e-2bb9e13301b5)

**Comment by tunacicek** [comment]
If you download an extract the file: 
* navigate into the folder 
* execute helm install hub -n semantics . (instead of the charts/semantic-hub

The documentation describes the installation if you are checkout the semantic-hub repository and execute the command from the root folder. 

Let me know, it that is working?

**Comment by FaridLU** [comment]
> If you download an extract the file:
> 
> * navigate into the folder
> * execute helm install hub -n semantics . (instead of the charts/semantic-hub
> 
> The documentation describes the installation if you are checkout the semantic-hub repository and execute the command from the root folder.
> 
> Let me know, it that is working?

Dear @tunacicek, thanks for your reply.

I tried that command in the newly downloaded released folder. It runs only the semantic-hub; it doesn't execute `keycloak` and `postgres`.

I then looked into the `values.yml` file to check the values there. I noticed that in some cases, the provided configs in `README.md` don't match the `values.yml` file. `enableKeycloak` is an example of this. In the `README.md`, it suggested making it `true`, but in the `values.yml` file, it is `false`.

Then I made a couple of changes in the `values.yml` file which are the following:
    
    enableKeycloak: true
    keycloak.postgresql.enabled: true

By making that change, I was able to run 3 services `hub`, `postgresql`, and `keycloak`. Unfortunately, except `keycloak`, both of those are not running.

![image](https://github.com/user-attachments/assets/5c93eb17-659d-4b27-88d6-c4f7681ff523)

Can you please help me out now? TIA.

**Comment by tunacicek** [comment]
Hi @FaridLU Thanks for your input. 
I checked it again and the bug is in the keycloak/init-script-configmap.yaml:
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/b7c9c4cb1729d5df3f6befb42feb303b2a46151d/charts/semantic-hub/templates/keycloak/init-script-configmap.yaml#L23

The configMap is created with hub.fullname and the reference in the values.yml is not correct. 
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/b7c9c4cb1729d5df3f6befb42feb303b2a46151d/charts/semantic-hub/values.yaml#L121

This needs to be fixed. Thanks again for your issue ticket.
 Until the bug fixed the workaround is: 
 If you not overwrite the hub.fullname param in the values.yml, use the following configuration: 
 ```
keycloak:
  postgresql:
    enabled: true
  auth:
    adminUser: user
    adminPassword: pw
  service:
    type: ClusterIP
  extraVolumes:
    - name: hub-semantic-hub-keycloak-init-script-configmap
      configMap:
        name: hub-semantic-hub-keycloak-init-script-configmap
  # Mounting a keycloak realm configuration file
  fullnameOverride: hub-keycloak
  extraVolumeMounts:
    - mountPath: /opt/keycloak/data/import/default-realm-import.json
      subPath: default-realm-import.json
      name: hub-semantic-hub-keycloak-init-script-configmap
```
